version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - localnet
    depends_on:
      - redis
  redis:
    image: redis
    networks:
      - localnet
networks:
  localnet:
    driver: bridge